/*
 * Generated API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ml.raketeufo.thirestbridge.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Adresse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-05T00:54:42.271211+02:00[Europe/Berlin]")
public class Adresse {
  @SerializedName("ort")
  private String ort = null;

  @SerializedName("plz")
  private String plz = null;

  @SerializedName("str")
  private String str = null;

  public Adresse ort(String ort) {
    this.ort = ort;
    return this;
  }

   /**
   * Get ort
   * @return ort
  **/
  @Schema(description = "")
  public String getOrt() {
    return ort;
  }

  public void setOrt(String ort) {
    this.ort = ort;
  }

  public Adresse plz(String plz) {
    this.plz = plz;
    return this;
  }

   /**
   * Get plz
   * @return plz
  **/
  @Schema(description = "")
  public String getPlz() {
    return plz;
  }

  public void setPlz(String plz) {
    this.plz = plz;
  }

  public Adresse str(String str) {
    this.str = str;
    return this;
  }

   /**
   * Get str
   * @return str
  **/
  @Schema(description = "")
  public String getStr() {
    return str;
  }

  public void setStr(String str) {
    this.str = str;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Adresse adresse = (Adresse) o;
    return Objects.equals(this.ort, adresse.ort) &&
        Objects.equals(this.plz, adresse.plz) &&
        Objects.equals(this.str, adresse.str);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ort, plz, str);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Adresse {\n");
    
    sb.append("    ort: ").append(toIndentedString(ort)).append("\n");
    sb.append("    plz: ").append(toIndentedString(plz)).append("\n");
    sb.append("    str: ").append(toIndentedString(str)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
