/*
 * Generated API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ml.raketeufo.thirestbridge.api.model;

import java.io.Serializable;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.LocalDateTime;
/**
 * CourseEvent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-05T00:54:42.271211+02:00[Europe/Berlin]")
public class CourseEvent implements Serializable {
  @SerializedName("end")
  private LocalDateTime end = null;

  @SerializedName("start")
  private LocalDateTime start = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("dozent")
  private String dozent = null;

  @SerializedName("ects")
  private Integer ects = null;

  @SerializedName("fach")
  private String fach = null;

  @SerializedName("inhalt")
  private String inhalt = null;

  @SerializedName("literatur")
  private String literatur = null;

  @SerializedName("pruefung")
  private String pruefung = null;

  @SerializedName("room")
  private String room = null;

  @SerializedName("studiengang")
  private String studiengang = null;

  @SerializedName("studiengruppe")
  private String studiengruppe = null;

  @SerializedName("sws")
  private Integer sws = null;

  @SerializedName("teilgruppe")
  private Integer teilgruppe = null;

  @SerializedName("ziel")
  private String ziel = null;

  public CourseEvent end(LocalDateTime end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @Schema(description = "")
  public LocalDateTime getEnd() {
    return end;
  }

  public void setEnd(LocalDateTime end) {
    this.end = end;
  }

  public CourseEvent start(LocalDateTime start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @Schema(description = "")
  public LocalDateTime getStart() {
    return start;
  }

  public void setStart(LocalDateTime start) {
    this.start = start;
  }

  public CourseEvent title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public CourseEvent dozent(String dozent) {
    this.dozent = dozent;
    return this;
  }

   /**
   * Get dozent
   * @return dozent
  **/
  @Schema(description = "")
  public String getDozent() {
    return dozent;
  }

  public void setDozent(String dozent) {
    this.dozent = dozent;
  }

  public CourseEvent ects(Integer ects) {
    this.ects = ects;
    return this;
  }

   /**
   * Get ects
   * @return ects
  **/
  @Schema(description = "")
  public Integer getEcts() {
    return ects;
  }

  public void setEcts(Integer ects) {
    this.ects = ects;
  }

  public CourseEvent fach(String fach) {
    this.fach = fach;
    return this;
  }

   /**
   * Get fach
   * @return fach
  **/
  @Schema(description = "")
  public String getFach() {
    return fach;
  }

  public void setFach(String fach) {
    this.fach = fach;
  }

  public CourseEvent inhalt(String inhalt) {
    this.inhalt = inhalt;
    return this;
  }

   /**
   * Get inhalt
   * @return inhalt
  **/
  @Schema(description = "")
  public String getInhalt() {
    return inhalt;
  }

  public void setInhalt(String inhalt) {
    this.inhalt = inhalt;
  }

  public CourseEvent literatur(String literatur) {
    this.literatur = literatur;
    return this;
  }

   /**
   * Get literatur
   * @return literatur
  **/
  @Schema(description = "")
  public String getLiteratur() {
    return literatur;
  }

  public void setLiteratur(String literatur) {
    this.literatur = literatur;
  }

  public CourseEvent pruefung(String pruefung) {
    this.pruefung = pruefung;
    return this;
  }

   /**
   * Get pruefung
   * @return pruefung
  **/
  @Schema(description = "")
  public String getPruefung() {
    return pruefung;
  }

  public void setPruefung(String pruefung) {
    this.pruefung = pruefung;
  }

  public CourseEvent room(String room) {
    this.room = room;
    return this;
  }

   /**
   * Get room
   * @return room
  **/
  @Schema(description = "")
  public String getRoom() {
    return room;
  }

  public void setRoom(String room) {
    this.room = room;
  }

  public CourseEvent studiengang(String studiengang) {
    this.studiengang = studiengang;
    return this;
  }

   /**
   * Get studiengang
   * @return studiengang
  **/
  @Schema(description = "")
  public String getStudiengang() {
    return studiengang;
  }

  public void setStudiengang(String studiengang) {
    this.studiengang = studiengang;
  }

  public CourseEvent studiengruppe(String studiengruppe) {
    this.studiengruppe = studiengruppe;
    return this;
  }

   /**
   * Get studiengruppe
   * @return studiengruppe
  **/
  @Schema(description = "")
  public String getStudiengruppe() {
    return studiengruppe;
  }

  public void setStudiengruppe(String studiengruppe) {
    this.studiengruppe = studiengruppe;
  }

  public CourseEvent sws(Integer sws) {
    this.sws = sws;
    return this;
  }

   /**
   * Get sws
   * @return sws
  **/
  @Schema(description = "")
  public Integer getSws() {
    return sws;
  }

  public void setSws(Integer sws) {
    this.sws = sws;
  }

  public CourseEvent teilgruppe(Integer teilgruppe) {
    this.teilgruppe = teilgruppe;
    return this;
  }

   /**
   * Get teilgruppe
   * @return teilgruppe
  **/
  @Schema(description = "")
  public Integer getTeilgruppe() {
    return teilgruppe;
  }

  public void setTeilgruppe(Integer teilgruppe) {
    this.teilgruppe = teilgruppe;
  }

  public CourseEvent ziel(String ziel) {
    this.ziel = ziel;
    return this;
  }

   /**
   * Get ziel
   * @return ziel
  **/
  @Schema(description = "")
  public String getZiel() {
    return ziel;
  }

  public void setZiel(String ziel) {
    this.ziel = ziel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CourseEvent courseEvent = (CourseEvent) o;
    return Objects.equals(this.end, courseEvent.end) &&
        Objects.equals(this.start, courseEvent.start) &&
        Objects.equals(this.title, courseEvent.title) &&
        Objects.equals(this.dozent, courseEvent.dozent) &&
        Objects.equals(this.ects, courseEvent.ects) &&
        Objects.equals(this.fach, courseEvent.fach) &&
        Objects.equals(this.inhalt, courseEvent.inhalt) &&
        Objects.equals(this.literatur, courseEvent.literatur) &&
        Objects.equals(this.pruefung, courseEvent.pruefung) &&
        Objects.equals(this.room, courseEvent.room) &&
        Objects.equals(this.studiengang, courseEvent.studiengang) &&
        Objects.equals(this.studiengruppe, courseEvent.studiengruppe) &&
        Objects.equals(this.sws, courseEvent.sws) &&
        Objects.equals(this.teilgruppe, courseEvent.teilgruppe) &&
        Objects.equals(this.ziel, courseEvent.ziel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(end, start, title, dozent, ects, fach, inhalt, literatur, pruefung, room, studiengang, studiengruppe, sws, teilgruppe, ziel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CourseEvent {\n");
    
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    dozent: ").append(toIndentedString(dozent)).append("\n");
    sb.append("    ects: ").append(toIndentedString(ects)).append("\n");
    sb.append("    fach: ").append(toIndentedString(fach)).append("\n");
    sb.append("    inhalt: ").append(toIndentedString(inhalt)).append("\n");
    sb.append("    literatur: ").append(toIndentedString(literatur)).append("\n");
    sb.append("    pruefung: ").append(toIndentedString(pruefung)).append("\n");
    sb.append("    room: ").append(toIndentedString(room)).append("\n");
    sb.append("    studiengang: ").append(toIndentedString(studiengang)).append("\n");
    sb.append("    studiengruppe: ").append(toIndentedString(studiengruppe)).append("\n");
    sb.append("    sws: ").append(toIndentedString(sws)).append("\n");
    sb.append("    teilgruppe: ").append(toIndentedString(teilgruppe)).append("\n");
    sb.append("    ziel: ").append(toIndentedString(ziel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
