/*
 * Generated API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ml.raketeufo.thirestbridge.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Rueckmeldung
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-05T00:54:42.271211+02:00[Europe/Berlin]")
public class Rueckmeldung {
  @SerializedName("rueckgemeldet")
  private Boolean rueckgemeldet = null;

  @SerializedName("semester")
  private String semester = null;

  public Rueckmeldung rueckgemeldet(Boolean rueckgemeldet) {
    this.rueckgemeldet = rueckgemeldet;
    return this;
  }

   /**
   * Get rueckgemeldet
   * @return rueckgemeldet
  **/
  @Schema(description = "")
  public Boolean isRueckgemeldet() {
    return rueckgemeldet;
  }

  public void setRueckgemeldet(Boolean rueckgemeldet) {
    this.rueckgemeldet = rueckgemeldet;
  }

  public Rueckmeldung semester(String semester) {
    this.semester = semester;
    return this;
  }

   /**
   * Get semester
   * @return semester
  **/
  @Schema(description = "")
  public String getSemester() {
    return semester;
  }

  public void setSemester(String semester) {
    this.semester = semester;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rueckmeldung rueckmeldung = (Rueckmeldung) o;
    return Objects.equals(this.rueckgemeldet, rueckmeldung.rueckgemeldet) &&
        Objects.equals(this.semester, rueckmeldung.semester);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rueckgemeldet, semester);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rueckmeldung {\n");
    
    sb.append("    rueckgemeldet: ").append(toIndentedString(rueckgemeldet)).append("\n");
    sb.append("    semester: ").append(toIndentedString(semester)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
